#! /bin/bash

source ./functions


cd

local_dbdir=~/Dropbox/machine/$LOCALHOSTNAME
[[ -d $local_dbdir ]] || die "no such dir: $local_dbdir (run ./makeln first)"
[[ -d $local_dbdir/common ]] && die "common dir already in place; no need to run?"
[[ -d $mydir ]] || die "I appear not to exist ..."
[[ -L $mydir ]] && die "I'm linked *somewhere*, but not the *right* where ..."

mv $mydir $local_dbdir/common
make_link $local_dbdir/common $mydir
