#! /bin/bash

source ./functions


###########################
# MAIN
###########################

# although most of our common files are stored here and symlinked elsewhere,
# some of them can't practically be done that way (e.g. Mozilla files,
# which might be on a Windows box which wouldn't understand a symlink)
# this script refreshes our copies of those files

# Firefox sync'ing now done via Xmarks
# but leaving this script JIC we need the hook later
mozdir=$(find_mozilla_profile_dir)
# couldn't find it?  ah, well ... just skip it
# also have to give it a miss if we have no firefox dir yet
if [[ -d $mozdir && -d $mydir/firefox ]]
then
fi
