export CEROOT=/vagrant
export CE_REMOTE_USERNAME=bburden
export PERL5LIB=$CEROOT/lib:$CEROOT/extlib/lib/perl5:$CEROOT/tlib

if ! echo $PATH | fgrep -q $CEROOT/tmp/bin
then
	PATH=$PATH:$CEROOT/tmp/bin
fi

alias ls='ls -CF'
alias resrc='source ~/.bashrc'
alias pdoc=perldoc
alias reset_sandbox='$CEROOT/tmp/new_sandbox'
alias sqlr='sql rpt'
alias sqll='sql log'
