# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

###############
# HISTORY STUFF
#
# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000
#
# end HISTORY STUFF
###################

unalias -a
alias ls='ls -AF'
alias ll='ls -l'
alias lln='ll -htr'
alias lls='ls -lhSr'
alias dux='du -xh --max-depth=1 | grep -v "^0	" | sortk'
alias rehash='hash -r'
alias resrc='. ~/.bashrc'
alias psync='cd /root/common && ./psync && ./makeln && cd -'

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

if grep -q buddy /etc/passwd
then
	buddy=/home/buddy
elif grep -q bburden /etc/passwd
then
	buddy=/home/bburden
fi

if [[ -n $buddy && -d $buddy && -d $buddy/bin ]]
then
	addpath=$buddy/bin/addpath
	if [[ -x $addpath ]]
	then
		PATH=$($addpath -B /root/bin /usr/lib/ccache/bin /usr/lib64/ccache /bin /sbin /usr/bin /usr/sbin /usr/local/bin /opt/bin /usr/local/sbin /usr/lib64/qt-3.3/bin /usr/i686-pc-linux-gnu/gcc-bin/3.3.5-20050130)
	else
		echo "can't execute addpath; not adjusting path ..." >&2
	fi
else
	echo "can't find Buddy's home dir; not adjusting path ..." >&2
fi

# as per which man page
# although Linux Mint doesn't seem to have the super-cool which that Fedora did, so fallback to type
which ()
{
	if which --help >/dev/null 2>&1
	then
		(alias; declare -f) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
	else
		type $@
	fi
}
export -f which

export EDITOR=vim
export PAGER="less -RaF -x4 -j2"

export PS1="\[\e[31;1m\]\h \[\e[34;1m\]\w # \[\e[0m\]"

if [[ -e ~/.bashrc.local ]]
then
	source ~/.bashrc.local
fi

function dep
{
	/usr/bin/dep --colour=yes "$@" | grep -v '^!!! ebuild_dep_to_edb'
}

function ff
{
	find . -name /proc -prune -o -iname "*$@*" -print 2>/dev/null
}
