#! /usr/local/bin/launch bash -*PROJ:archer-boot -*DEVOPS
bashlib-demand ssh

host=$1 ; shift
host=$(archer-hostname $host)
function cessh { $ABOOTROOT/devtools/archer-ssh "$@" ; }
function cescp { $ABOOTROOT/devtools/archer-scp "$@" ; }

screen=monitor										# most machines are used for monitoring something
[[ $host == *@dirk* ]] && screen=logs				# but dirk is special in a couple of ways
[[ $host == *@quin* ]] && screen=push				# and quin's are even special-er

if ! cessh $host cat .bashrc | grep -q "^export CURRENT_SCREEN="
then
	cat <<END | cessh $host cat ">>.bashrc"

export CE_REMOTE_USERNAME=bburden
export PERL5LIB=\$CEROOT/lib:\$CEROOT/extlib/lib/perl5
[[ \$PATH == *\$HOME/bin* ]] || export PATH=\$PATH:\$HOME/bin
export PAGER="$PAGER"
export CURRENT_SCREEN=$screen
alias sr='screen -A -x \$CURRENT_SCREEN'
END
fi

cescp -p ~/.exrc $host:

if [[ $(cessh $host ls ".screenrc*" 2>/dev/null | wc -l) -lt 2 ]]
then
	cescp ~/common/rc/screenrc         $host:.screenrc
	cescp ~/common/rc/screenrc.$screen $host:.screenrc.$screen
fi

# set up for pjawk, but only on dirk
if [[ $screen == "logs" ]]
then
	cessh $host mkdir -p bin/
	cescp $(find ~/common/ -name build-pjawk) $host:bin/
fi
