#! /bin/bash

host=$1 ; shift

if ! cessh $host cat .bashrc | grep -q "^alias go="
then
	cat <<END | cessh $host cat ">>.bashrc"

export CEROOT=/var/local/CE
export CE_REMOTE_USERNAME=bburden
export PERL5LIB=\$CEROOT/lib:\$CEROOT/extlib/lib/perl5
export PAGER="$PAGER"
alias go='sudo -H -u CE -i'
END
fi
