#! /usr/bin/env perl

use myperl::Pxb;
use autodie ':all';

const my $CEROOT => $ENV{CEROOT} // fatal('must set $CEROOT first!');


opts <<'-';
	[-vD] { -e <pattern> | <pattern> }
	-v : be more verbose
	-D : debug mode (implies -v)
	-e : next arg is the <pattern>, even if it starts with -
	<pattern> : Perl-style regex
-
$OPT{v} = 1 if $OPT{D};

my $regex = $OPT{e} // shift // usage_error('must supply regex');
$regex = qr/$regex/;


my @ignores =
	map  { -d ? ('--ignore-dir' => $_) : -f ? ('--ignore-file' => $_) : die("can't identify: $_") }
	map  { glob("$CEROOT/$_") }
	grep { /extlib/ && ! /^#/ }
		 ( path("$CEROOT/.gitignore")->slurp(chomp => 1) )
;
my @opts = $OPT{D} ? '-x' : ();
sh(@opts, ack => @ignores => "$CEROOT/extlib" => '--match' => $regex);
