#! /bin/bash -e

function show-mem
{
	echo "$1"
	perl -le 'print "=" x length(shift)' "$1"
	free -h
	echo
}

show-mem "BEFORE:"

echo "turning off swap"
swapoff -a
echo

show-mem "DURING:"

echo "re-enabling swap"
systemctl restart zram-config.service
swapon -a
echo

show-mem "AFTER:"
swapon -s
