#! /bin/bash


# determine the wired interface
# it used to always be eth0, but nowadays, not so much
function eth0
{
	for interface in $(ifconfig -s -a | awk 'NR > 1 {print $1}')
	do
		if ethtool $interface 2>/dev/null | grep -q "Supported ports"
		then
			echo $interface
			break
		fi
	done
}


# figure out whether we're going to connect or not
function network_up
{
	#route | tail -n +3
	[[ $(route | tail -n +3 | wc -l) -ge 2 ]]
}

# this usually fixes it
service network-manager restart

echo -n "waiting for reconnect "
for n in $(seq 1 20)
do
	echo -n "."
	sleep 1
	if network_up
	then
		echo " and we're up"
		exit
	fi
done

# this is a bit more intrusive,
# but fixes some things the above doesn't
echo -ne "\ngoing deeper "
ip link set $(eth0) down
ip link set $(eth0) up

for n in $(seq 1 20)
do
	echo -n "."
	sleep 1
	if network_up
	then
		echo " and we're up"
		exit
	fi
done

echo " tired of waiting"
# go extreme
echo "going medieval on its ass"
basemod=$(lsmod | awk '{print $1}' | grep 'iwl.vm')
rmmod $basemod
rmmod iwlwifi
modprobe $basemod iwlwifi
lsmod | grep iwlwifi

if network_up
then
	echo "success!"
else
	echo "out of tricks"
fi
