#! /bin/bash

readonly me=${0##*/}

group="$1"
newgroup="$2"

if [[ -z $group || -z $newgroup ]]
then
	echo "usage: $me groupname new_groupname_for_existing_users" >&2
	exit
fi

gid=$(awk -F: '$1 == "'$group'" {print $3}' /etc/group)
if [[ -z $gid ]]
then
	echo "$me: that group doesn't exist, twit" >&2
	exit 2
fi

if [[ -z $(awk -F: '$1 == "'$newgroup'"' /etc/group) ]]
then
	echo "$me: the group you want to switch users to doesn't exist, moron" >&2
	exit 2
fi

users="$(awk -F: '$4 == '$gid' { print $1 }' /etc/passwd)"
if [[ -n $(awk -F: '$3 == '$newgid /etc/group) ]]
then
	echo "$me: hey sunshine! that gid already exists!  you're asking for a world of hurt baby ..." >&2
	exit 1
fi

echo "changing group $group from $oldgid to $newgid"
echo -n "you sure? [y/N] "
read yn

if [[ $yn == [yY]* ]]
then
	/usr/sbin/groupmod -g $newgid $group
	/usr/bin/find / -path /proc -prune -o -group $oldgid -exec chgrp $group {} \;
fi
