#!/bin/bash

# Directory where logs will be stored
LOG_DIR=/var/log/system-monitor
mkdir -p $LOG_DIR

# Current time for file naming
LOG_TIME=$(date +"%Y%m%d-%H%M")

# Filename pattern
LOG_FILE=$LOG_DIR/$LOG_TIME.log

# Function to log messages
function log
{
    echo "$(date +'%Y-%m-%d %H:%M:%S') - $1" >>$LOG_FILE
}

# Function to check command success
function run_command
{
    bash -c "$*" >>$LOG_FILE 2>&1 || log "Error: Failed to get results [$1]"
}

log "Starting system monitor"

# Collect information
log "=== Temperature ==="
run_command "sensors"

log "=== Battery Status ==="
run_command "upower -i /org/freedesktop/UPower/devices/battery_BAT0"
run_command "cat /sys/class/power_supply/BAT0/status"

log "=== Latest Graphics Driver Errors ==="
run_command "dmesg | grep i915 | tail -n 10"

log "=== System Load ==="
run_command "uptime"
run_command "ps -eo %cpu,%mem,cmd --sort=-%cpu | head -n 5"

log "=== Disk Health ==="
INTERESTING_ATTRIBS="Temperature:|Percentage Used:|Power On Hours:|Data Units Read:|Data Units Written:"
INTERESTING_ATTRIBS="$INTERESTING_ATTRIBS|Media and Data Integrity Errors:|Error Information Log Entries:|Unsafe Shutdowns:"
run_command "smartctl -x /dev/nvme0n1 | egrep '$INTERESTING_ATTRIBS'"

log "=== Memory Usage ==="
run_command "free -h"

log "=== Disk Usage ==="
run_command "df -h"

log "=== Service Status ==="
run_command "systemctl status system-monitor.service"

# Delete old logs:
log "Cleaning up old logs"
if [[ $(perl -lne '/^(\d+)/ and print int($1 / 60 / 60)' /proc/uptime) -lt 48 ]]
then
	: # The system has been up for less than 2 days; don't clean up anything recent.
else
	# 1: Minutely logs older than 2 hours
	find $LOG_DIR -type f -not -name '*-??00.log' -mmin +120 -delete || log "Error: Failed to delete old minutely logs"
	# 2: Hourly logs older than 2 days
	find $LOG_DIR -type f -not -name '*-0000.log' -mtime +2 -delete || log "Error: Failed to delete old hourly logs"
fi
# 3: Daily logs older than 2 weeks
find $LOG_DIR -type f -name '*.log' -mtime +14 -delete || log "Error: Failed to delete old daily logs"

log "System monitor completed"
