#! /bin/bash


file=$(type -P $1)


###############
##  MANDRAKE ##
###############

if type urpmf >/dev/null 2>&1
then
	identified=1

	urpmf $file
fi


##############
##  FEDORA  ##
##############

if type yum >/dev/null 2>&1
then
	identified=1

	yum -C --noplugins provides $file | perl -lne 'BEGIN { $/ = "" } /^(\d:)?(.*)$/m and print $2 if /installed/'
fi


##############
##  GENTOO  ##
##############

if type emerge >/dev/null 2>&1
then
	identified=1

	if [[ -n $file ]]
	then
		if type etool >/dev/null 2>&1
		then
			etool -f $file
		else
			equery belongs $file
		fi
	fi
fi


###########
##  ???  ##
###########

if [[ ! $identified ]]
then
	echo "$me: can't seem to figure out what distro you're using" >&2
	exit 1
fi
